### ISSUE TITLE
Resest OAuth

### ISSUE THREAD

**Issue by acmiller24** [jdevoo/twecoll#13]
Great tool, thanks. How do I reset the OAuth? It does not seem to be giving me access any longer.

**Comment by jdevoo** [comment]
try deleting the .twecoll file which is in the home directory. The script will invite you to re-register and fetch the new tokens.

**Comment by acmiller24** [comment]
ok, must be a different problem.  It looks like the error is specific to a particular user (I'm guessing with a private account): "HTTPError 401 with 93361520. Skipping...Done." But, I only seem to be getting a small number of friends downloaded using the fetch command even though the total number of followers is under 3,000.

**Comment by jdevoo** [comment]
yes that's right - if you use twecoll resolve followed by the account ID, you will find the name and notice that "@tussy555's Tweets are protected."
The low count on fetch can be changed with twecoll fetch -c 40000 for example. The '-c' sets the upper limit like 40.000 in my example.

**Comment by acmiller24** [comment]
got it, thanks for the reply!
