### ISSUE TITLE
What is lfr and ffr?

### ISSUE THREAD

**Issue by ftrotter** [jdevoo/twecoll#14]
They are in your code, and in the resulting data, but is not clear what they mean?

-FT

**Comment by jdevoo** [comment]
They are ratios, specifically List-to-Follower Ration and Friends-to-Follower Ratios. I had come across Valdis Krebs' post [Back of the Envelope Twitter Metrics](http://www.thenetworkthinkers.com/2010/08/back-of-envelope-twitter-metrics.html). I found them only marginally useful in my own uses. I think today of listed counts as another count to be added to followers considering those who follow via lists...
