### ISSUE TITLE
Retweet graph

### ISSUE THREAD

**Issue by ftrotter** [jdevoo/twecoll#15]
I think the follower map on Twitter is very interesting, but I would be more interested in the retweet graph. i.e. among a group of followers, starting from a particular user... do the users retweet each other...

Is that something that twecoll could easily implement?

Thank you for the wonderfully simple and useful tool.

Regards,
-FT

**Comment by lucahammer** [comment]
I don't think it could be easily implemented, but it could use some parts (like getting tweets) of twecoll.

What would be an edge? If a user retweeted someone? Or if they retweeted each other? 
How deep should it go? Get x tweets from User y, for each tweet that got retweeted, get the IDs of people who retweeted it. Get x tweets from each of the retweeters and so on.

**Comment by jdevoo** [comment]
I have been also thinking about that... there are for example fantastic conversations going on with the US presidential elections looking at tweets like this one... https://twitter.com/SenWarren/status/730840526291910656

Unfortunately, there doesn't seem to be a simple API way yet to support this as @lucahammer hinted... I had checked the forum and noticed Andy Piper's note towards the bottom https://twittercommunity.com/t/view-conversations-api-support/11090/37

The conversations form potentially complex trees as anyone can start from the thread example above and start a side convo...

**Comment by ftrotter** [comment]
The implementation that I think would be most generically relevant would be

Spider the follower list as happens now.
Get the last 1000 tweets for each user.
For each tweet: 
add (or increment the weight of) a retweet edge if the tweet is a retweet of the user on the graph
add (or increment the weight of) a quote edge if the tweet contains a quote of a tweet of a user on the graph
add (or increment the weight of) the reply edge if the tweet is in reply to a tweet of a user on the graph.

For dense follower graphs (I follow lots of users who typically follow lots of users, including the users I follow) the actual frequency of retweets and other interactions is a much better measure of the "weight" between follower connections than anything else. 

This ignores entirely the problem of trying to "walk the reply tree" or "walk the retweet tree", which would also be cool, but would require vastly more API calls to implement correctly. By limiting everything to a depth of one, it would be time consuming to run, but not too hard to implement. 

Of course, this would probably take days to download even with the limitation of the last 1000 tweets for each user... but it would be wicked cool data.

-FT

**Comment by jdevoo** [comment]
oh ok, that's not the same.
So there are these calls https://dev.twitter.com/rest/reference/get/statuses/retweets/%3Aid
https://dev.twitter.com/rest/reference/get/statuses/retweeters/ids
Would the second be interesting?

**Comment by ftrotter** [comment]
Yeah that call is much easier then the algo that I suggested... no need to trawl the tweets, instead just trawl the followers of the starting user, and then run this single call on each one... much more efficient and much faster....

**Comment by ftrotter** [comment]
On second thought, you would still need to get a list of recent tweets from the user... but those tweets will tell you clearly which tweets were retweeted... 

The tweets also show users that were @ mentioned.. so you could easily get a graph of @mentions easily from the single call to the recent tweets....

**Comment by jdevoo** [comment]
closing this as I implemented the feature in [nucoll](https://github.com/jdevoo/nucoll) and am not planning to further maintain twecoll
