### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by keithlee2010** [jdevoo/twecoll#16]
Hi!  I just downloaded and tried to run it.  I get the following:

File "./twecoll", line 473
    id0 = {user_id: val[0] for user_id, val in dat.iteritems() if val[1] in args.screen_name}

-KL

**Comment by jdevoo** [comment]
Hi Keith!! So you ran init and fetch and got stuck at edgelist?
How did you invoke it? That looks like part of the error - was there more?

**Comment by Penworks** [comment]
I have just used it yesterday and appeared to have no problems though
edgelist was created in a few seconds which surpised me as Id been led to
believe it would take a long time. This is the first time Ive used twecoll
so have no other experience to go on.

The imported gml in Gephi looks normal though.




*- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - *
*MSc MA MBCS FHEA*
*penworks.net <http://penworks.net/> | **@penworks
<http://www.twitter.com/penworks> | **skype:penworkz*

**Comment by jdevoo** [comment]
Without igraph, twecoll just generates the GML file and finishes faster leaving heavy visualization lifting to e.g. Gephi
