### ISSUE TITLE
Problem collecting data.

### ISSUE THREAD

**Issue by jaruizso** [jdevoo/twecoll#18]
I have a question regarding an error. I believe this error is because there was a Internet disconnection. I solved it by running again twecoll fetch. However, the program did something I did not expect. My question is then, after restarting the script, why it went back to collect data which was previously collected, and later jumps until where it was before the Internet connection problem?

Find below the code to understand better:

HTTPError 429 at 20:48. Waiting 15m to resume (8564 items left)...
Processing 1277878784...
Processing 2814630924...
**<urlopen error [Errno -2] Name or service not known>**
pi@raspberrypi:~/Desktop/twecoll $ python twecoll fetch "fullExport2"
Processing 455956478...
HTTPError 401 with 455956478. Skipping...
Processing 979104499...
HTTPError 401 with 979104499. Skipping...
Processing 983328241...
HTTPError 401 with 983328241. Skipping...
Processing 740795770014683136...
HTTPError 401 with 740795770014683136. Skipping...
Processing 346750636...
HTTPError 401 with 346750636. Skipping...
Processing 762921241414144000...
HTTPError 401 with 762921241414144000. Skipping...
Processing 2427376529...
HTTPError 401 with 2427376529. Skipping...
Processing 2188828472...
HTTPError 401 with 2188828472. Skipping...
Processing 1204197542...
HTTPError 401 with 1204197542. Skipping...
Processing 712010124504780800...
HTTPError 401 with 712010124504780800. Skipping...
Processing 485198649...
HTTPError 401 with 485198649. Skipping...
Processing 2614611833...
HTTPError 401 with 2614611833. Skipping...
Processing 238970728...
HTTPError 401 with 238970728. Skipping...
Processing 2419280250...
HTTPError 401 with 2419280250. Skipping...
Processing 759505530108973056...
HTTPError 401 with 759505530108973056. Skipping...
Processing 4135831001...
HTTPError 429 at 21:31. Waiting 15m to resume **(11443 items left)**...
Processing 4135831001...
HTTPError 401 with 4135831001. Skipping...
Processing 348384526...
HTTPError 401 with 348384526. Skipping...
Processing 729221168184623104...
HTTPError 401 with 729221168184623104. Skipping...
Processing 703995826...
HTTPError 401 with 703995826. Skipping...
Processing 1165903134...
HTTPError 401 with 1165903134. Skipping...
Processing 1692064393...
HTTPError 401 with 1692064393. Skipping...
Processing 777598742753112064...
HTTPError 401 with 777598742753112064. Skipping...
Processing 2445408019...
HTTPError 401 with 2445408019. Skipping...
Processing 2755043344...
HTTPError 401 with 2755043344. Skipping...
Processing 2523251996...
HTTPError 401 with 2523251996. Skipping...
Processing 333058829...
HTTPError 401 with 333058829. Skipping...
Processing 548284207...
HTTPError 401 with 548284207. Skipping...
Processing 915499807...
HTTPError 401 with 915499807. Skipping...
Processing 278683371...
HTTPError 401 with 278683371. Skipping...
Processing 754786801605279744...
HTTPError 401 with 754786801605279744. Skipping...
Processing 420584458...
HTTPError 429 at 21:47. Waiting 15m to resume **(10688 items left)**...
Processing 420584458...
HTTPError 401 with 420584458. Skipping...
Processing 728086226...
HTTPError 401 with 728086226. Skipping...
Processing 3227640515...
HTTPError 401 with 3227640515. Skipping...
Processing 763426385985757189...
HTTPError 401 with 763426385985757189. Skipping...
Processing 894072607...
HTTPError 401 with 894072607. Skipping...
Processing 174046229...
HTTPError 401 with 174046229. Skipping...
Processing 757706940764000256...
HTTPError 401 with 757706940764000256. Skipping...
Processing 2199291223...
HTTPError 401 with 2199291223. Skipping...
Processing 549302496...
HTTPError 401 with 549302496. Skipping...
Processing 518580822...
HTTPError 401 with 518580822. Skipping...
Processing 542590791...
HTTPError 401 with 542590791. Skipping...
Processing 3368799917...
HTTPError 401 with 3368799917. Skipping...
Processing 4483120175...
HTTPError 401 with 4483120175. Skipping...
Processing 37389342...
HTTPError 401 with 37389342. Skipping...
Processing 149512577...
HTTPError 401 with 149512577. Skipping...
Processing 701459716845731840...
HTTPError 429 at 22:02. Waiting 15m to resume **(9981 items left)**...
Processing 701459716845731840...
HTTPError 401 with 701459716845731840. Skipping...
Processing 1360067796...
HTTPError 401 with 1360067796. Skipping...
Processing 91198608...
HTTPError 401 with 91198608. Skipping...
Processing 3401588199...
HTTPError 401 with 3401588199. Skipping...
Processing 346777689...
HTTPError 401 with 346777689. Skipping...
Processing 41638738...
HTTPError 401 with 41638738. Skipping...
Processing 15335468...
HTTPError 401 with 15335468. Skipping...
Processing 1511618528...
HTTPError 401 with 1511618528. Skipping...
Processing 2350188882...
HTTPError 404 with 2350188882. Skipping...
Processing 107654185...
HTTPError 401 with 107654185. Skipping...
Processing 4795645257...
HTTPError 401 with 4795645257. Skipping...
Processing 717491524582383618...
HTTPError 401 with 717491524582383618. Skipping...
Processing 714027263788982273...
HTTPError 401 with 714027263788982273. Skipping...
Processing 1112659710...
HTTPError 401 with 1112659710. Skipping...
Processing 1413408344...
HTTPError 401 with 1413408344. Skipping...
Processing 4187643617...
HTTPError 429 at 22:18. Waiting 15m to resume **(8939 items left)**...
Processing 4187643617...
HTTPError 401 with 4187643617. Skipping...
Processing 549048484...
HTTPError 401 with 549048484. Skipping...
Processing 214242505...
HTTPError 401 with 214242505. Skipping...
Processing 587367573...
HTTPError 401 with 587367573. Skipping...
Processing 4690380504...
HTTPError 401 with 4690380504. Skipping...
Processing 2814630924...
Processing 1614584052...
Processing 140782566...
Processing 737307356703383552...
Processing 424208099...
Processing 1368863274...
Processing 3296594749...
HTTPError 404 with 3296594749. Skipping...
Processing 151443076...
Processing 137989363...
HTTPError 429 at 22:34. Waiting 15m to resume **(8555 items left).**..
Processing 137989363...
Processing 716668060833329152...
Processing 380526746...
Processing 371932423...
Processing 1381844899...
Processing 123171022...
Processing 372238505...
Processing 490197240...
Processing 3974988947...
Processing 280939961...
Processing 98785063...
Processing 135129703...
Processing 885952021...

Why these jumps? It is all normal and all right?

In adition, and even if its not related to this, I also encountered the problem `list index out of range`. And as described [here](https://github.com/jdevoo/twecoll/issues/12) by @lucahammer , I solved by deleting the empty line. No idea why this happened.

Thanks in advance,
Javier

**Comment by jdevoo** [comment]
The jumps are currently normal when repeating a run after some interruption. This can be CTRL-C or one of those Errno -2 which I was not yet able to isolate. There's a separate issue for that one. The tool does not save the last processed handle and restarts from the top of the dat file. It issues these skip statements for protected handles until it meets a handle for which there is no file in the fdat folder that is not protected.

**Comment by jaruizso** [comment]
In my case I think was a problem with the Internet. Because when I realized I lost Internet connection, I checked and the error was there.

So I understand then, the jumps are normal and there is no loss of data.
