### ISSUE TITLE
mentions VS friends

### ISSUE THREAD

**Issue by jaruizso** [jdevoo/twecoll#19]
I collected  a following/followee network of a hashtag with the help of @lucahammer , and using his modified script:

twecoll tweets -q "#hashtag"
twecoll init -q "#hashtag"
twecoll fetch "hashtag"
twecoll edgelist "hashtag"

However, when I open the file in Gephi, I see mention and friends types. I do not know why this happens, since I wanted to create just the following/followee network of the accounts found inside a hashtag.

Any suggestions?

![captura de pantalla 2016-11-26 a les 19 38 08](https://cloud.githubusercontent.com/assets/12252768/20642472/ed6d5f8a-b40f-11e6-82e3-4551ca812cdf.png)

**Comment by jdevoo** [comment]
The type column in this case helps differentiating people tweeting with the hashtag vs people mentioned in the tweet along with the hashtag.

For example, below are tweets against #citizensensing
`
Thu Nov 24 19:12:06 +0000 2016 @jdevoo               Soundscape: Echantillonnage sonore à Genève https://t.co/HLlAH2vGTK via @IT_IS_GIS cc @mhaklay #citizensensing #urbangene
Thu Nov 24 16:22:13 +0000 2016 @jdevoo               The Quantified Community at Red Hook: Urban Sensing and Citizen Science in Low-Income Neighborhoods https://t.co/Z9BfswlGd1 #citizensensing
Thu Nov 24 07:05:16 +0000 2016 @jdevoo               Continuous data user–producer dialog for independent monitoring practices &amp; other #citizensensing recommendations https://t.co/JTjorr0pAK
Tue Nov 22 14:02:20 +0000 2016 @citizen_sense        Looking forward to discussing Data Stories and Citizen Sensing tomorrow at #UWEdigitalmedia  @id_uwe #IoT #bigdata #citizensensing
Mon Nov 21 21:52:20 +0000 2016 @PeterSmedt           RT @discomplex: #MakingSenseEU #AirPollution measuring #citizensensing in #Pristina with @SfCKmovement #PolicyLab4EU https://t.co/MRtXym7DSS
`
and below the resulting dat file
`
Thu Nov 24 19:12:06 +0000 2016 @jdevoo               Soundscape: Echantillonnage sonore à Genève https://t.co/HLlAH2vGTK via @IT_IS_GIS cc @mhaklay #citizensensing #urbangene
Thu Nov 24 16:22:13 +0000 2016 @jdevoo               The Quantified Community at Red Hook: Urban Sensing and Citizen Science in Low-Income Neighborhoods https://t.co/Z9BfswlGd1 #citizensensing
Thu Nov 24 07:05:16 +0000 2016 @jdevoo               Continuous data user–producer dialog for independent monitoring practices &amp; other #citizensensing recommendations https://t.co/JTjorr0pAK
Tue Nov 22 14:02:20 +0000 2016 @citizen_sense        Looking forward to discussing Data Stories and Citizen Sensing tomorrow at #UWEdigitalmedia  @id_uwe #IoT #bigdata #citizensensing
Mon Nov 21 21:52:20 +0000 2016 @PeterSmedt           RT @discomplex: #MakingSenseEU #AirPollution measuring #citizensensing in #Pristina with @SfCKmovement #PolicyLab4EU https://t.co/MRtXym7DSS
`
Only PeterSmedt, citizen_sense and jdevoo tweeted while others were mentioned.

**Comment by jaruizso** [comment]
I understand. Is there anyway then to suppress mention data? I mean, to accelerate the data collection, and collecting only those who tweeted in the hashtag.

**Comment by jdevoo** [comment]
just added option '-n' to init which stands for "no mention" - on the example above it generates a dat file with only 3 names for PeterSmedt, citizen_sense and jdevoo

**Comment by jaruizso** [comment]
I tried, and it works. But just with tweets collected from the own twecoll. The question is that I have already stored the tweets and metadata collected from other software (TCAT from Amsterdam University).

I tried to make the same format as twecoll .twt files, but unsuccessfully. I wonder if the format is the correct one. Have a look to the little sample:

` 1/8/16 10:37	@JePatriote	RT @janimine: #Denmark closes its borders to #Germany  #Schengen #migrantcrisis #LeaveEU #remain https://t.co/raqriqYQFH
1/8/16 10:38	@MarkInNorthWest	RT @janimine: #Denmark closes its borders to #Germany  #Schengen #migrantcrisis #LeaveEU #remain https://t.co/raqriqYQFH
1/8/16 10:38	@MAB97_	For schengen visa (@ Al-Raya Complex in Kuwait City, Al Asimah) https://t.co/HMREq84ZpU
1/8/16 10:39	@capellawega	RT @janimine: #Denmark closes its borders to #Germany  #Schengen #migrantcrisis #LeaveEU #remain https://t.co/raqriqYQFH
1/8/16 10:39	@GringoPeruano	RT @OpenEurope: Turkey to pull out of migrant deal with EU unless it obtains visa-free travel to Schengen area https://t.co/T6gPTDFbPa `


For some reason here it does not look as in the file. In the file, when opened, looks more as your example of tweets for #citizensensing: ordered in rows and columns which can be perfectly diferenciated.

**Comment by jdevoo** [comment]
perhaps we can just transform the raw data above? can you share a couple of lines? I cannot make where the record starts... and from the looks of it, data format and separator are all we need to tweak. Perhaps?

**Comment by jaruizso** [comment]
The data you have seen above has already been transformed. Original data is in TSV format. I tried to aggregate it following twt structure by passing it to excel, deleting the unnecessary columns, and adding `@` to the usernames. Have a look to the picture attached.

There is not that much to copy&paste from the terminal. If used _init -q -n_, it just says _Done._ after the first one. In the picture you can see how the twt file looks like. If used _init -q_, it processes everything, but when opening the dat file, all except one (the first) are mentions.

![captura de pantalla 2016-12-02 a les 15 15 25](https://cloud.githubusercontent.com/assets/12252768/20836987/3dbc6a58-b8a2-11e6-8e0a-9bc989edbcaf.png)

**Comment by jdevoo** [comment]
I was distracted - it is possible to ingest an arbitrary .twt file and no processing is required as twecoll just looks for the handles in a line. I took the one line above and indeed it yields a .dat file with a single record for @JePatriote - there's no problem from my perspective. With -n twecoll only looks up the handle that tweeted and without it, it looks up all others that were mentioned.
