### ISSUE TITLE
Error with urllib3

### ISSUE THREAD

**Issue by jugendhacker** [jdevoo/twecoll#23]
I edited the code so I use urllib3 and now I get this error:
```
Traceback (most recent call last):
  File "./twecoll", line 84, in <module>
    class Request(urllib3.request):
TypeError: module.__init__() takes at most 2 arguments (3 given)
```

**Comment by jdevoo** [comment]
That will lead to several changes including the oauth mechanism which uses a urllib2 custom opener.

**Comment by jugendhacker** [comment]
And how can I fix it?

**Comment by jdevoo** [comment]
I am not familiar with urllib3 and it seems to address different use cases.

**Comment by jugendhacker** [comment]
So it is not possible that I can use the script with urllib3?

**Comment by jdevoo** [comment]
I suggest you check their documentation. I will close this issue for now.
