### ISSUE TITLE
429 errors for large collections

### ISSUE THREAD

**Issue by jdevoo** [jdevoo/twecoll#24]
retrieving followers of http://twitter.com/okcthunder (1.8M+) throws 429 without retrieving a first block of 100 users - should POST be used?

**Comment by lucahammer** [comment]
Works for me, but the takes some time until all IDs are loaded and can be
processed.

Followers / Batches of IDs / requests per timeframe

1 500 000 / 5 000 / 15 = 20

There are at least twenty 429 errors before the processing starts.

**Comment by sanskarkatiyar** [comment]
I am getting a 429 for every 15 followers processed. Should there be an explicit delay between two successive requests?

**Comment by jdevoo** [comment]
on which handle? Could it be the same case as with the example above?

**Comment by jdevoo** [comment]
fetch will pause for 15 minutes every 15 or so handles - that is required by the Twitter API.
See https://developer.twitter.com/en/docs/basics/rate-limiting

You can use `twecoll -s` to find out how many requests are left before hitting the rate limit.

**Comment by sanskarkatiyar** [comment]
Oh, my bad! Thanks for the response and this wonderful script! 👍
