### ISSUE TITLE
twecoll edgelist: Visualization skipped

### ISSUE THREAD

**Issue by jeremiepoiroux** [jdevoo/twecoll#26]
Hi,
I do not remember well, but I guess I have the following error because I upgraded igraph. The project is now called python-igraph and it seems twecoll is lost with the new igraph.

Did someone got this message to? And found a solution?

> Visualization skipped. To avoid name collision with the igraph project, this visualization library has been renamed to ‘jgraph’. Please upgrade when convenient.

Thanks ! Best, Jérémie

**Comment by tarikaltuncu** [comment]
Hi,

you should do the following:
pip uninstall igraph
pip install python-igraph
