### ISSUE TITLE
Attribution for use in publication

### ISSUE THREAD

**Issue by usnish** [jdevoo/twecoll#29]
Hello! I'm planning to use twecoll in a scientific publication -- how would you prefer this project be attributed?

**Comment by jdevoo** [comment]
Hello and thanks for asking!! Not sure really. License is MIT. Author is me and Luca Hammer is a key contributor. If you use happen to use the visualization or metrics, a reference to the terrific igraph library would also be good. How did twecoll help as there are now so many R, Python packages out there?

**Comment by usnish** [comment]
Awesome! I'll make sure to link the project. Twecoll remained the most convenient way to download a large number of followers' information, with wait loops for the API rate limits and everything built in. I ran the script on a digitalocean instance over 4-5 days and everything worked great :) I'm a medical student on a tight schedule so your code saved me a lot of time!!

**Comment by jdevoo** [comment]
Great to hear this! I am trying to see which parts are most valuable as Python 2.7 code is near EOL.
