### ISSUE TITLE
HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by eifersuchtcl** [jdevoo/twecoll#3]
Hello i am new in python. Thank you for your script. What can i do about this?

C:\Python27>python twecoll.py fetch andigraf
Processing 117273797...

HTTP Error 401: Unauthorized

**Comment by jdevoo** [comment]
An HTTP Error 401 will be thrown if the supplied key and secret cannot be used to retrieve the access token details e.g. typo
