### ISSUE TITLE
SyntaxError: invalid syntax line 121

### ISSUE THREAD

**Issue by Daemoni19478** [jdevoo/twecoll#31]
Hi, first i'm not a developer, just a curious CM. I'm trying to use twecoll with python for make graphics of followers and hashtags. It's the first time i use it.  When i tried, this is what happened:

PS C:\twecoll> python twecoll init sisepuedesanse –followers
  File "twecoll", line 121
    query = map(lambda (k, v): (k, urllib.quote(v)), urlparse.parse_qsl(query))
                       ^
SyntaxError: invalid syntax

Could anyone help me with this? 

Thanks

**Comment by jdevoo** [comment]
Did you modify the script? I just ran the following commands with success using the latest version 1.13

`twecoll init sisepuedesanse --folowers`

`twecoll init --followers sisepuedesanse`

the parameter followers or 'o' is preceded by double dash or single dash respectively.

**Comment by joeylowe** [comment]
Hi! I'm in a similar situation and I'm running Python 3.6. I assume that's the issue.  Is there a version of twecoll that runs on 3.6?  I use this version for so many other things.  I do have 2.7 installed on this Windows machine but I have no idea how to specify which version of Python for a script to use.  Thanks for your advice.

**Comment by jdevoo** [comment]
I should take the time to upgrade to Python 3...
You can specify which version in the first line after shebang followed by the path to the Python you want. Example shebangs with real paths such as #!C:\Python27\python.exe.
There are other ways though.

**Comment by joeylowe** [comment]
Thanks for fast reply sir. Yes, the real path worked good!  I wasn't sure if you were actively working on this script anymore so I started going through it last night in an attempt to upgrade to 3. If okay, I'll send you what I do over the weekend and see if that helps it along or not.

**Comment by jdevoo** [comment]
oh fantastic! thank you! I had identified a resource for helping at http://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html

**Comment by jdevoo** [comment]
see #38
