### ISSUE TITLE
field larger than field limit (131072)

### ISSUE THREAD

**Issue by ChrisBolman** [jdevoo/twecoll#32]
looking to run edgelist on a large collection and can't get around the "field larger than field limit (131072)" err. 

have tried updating edgelist function to increase `field_size_limit` w/ `csv.field_size_limit(sys.maxsize)`

is there a best practice recommendation around this or is my data set too large?

thanks

**Comment by jdevoo** [comment]
Hello Chris! can you elaborate on the data? Perhaps worth commenting out the try/excepts/else in main() to have more infos?

**Comment by ChrisBolman** [comment]
It was a .csv of about 1 GB. I was in err, including `csv.field_size_limit(sys.maxsize)` **is** the correct solution. I had it nested inside a function - I've resolved the issue by fixing my code. thanks
