### ISSUE TITLE
python 3 compatible

### ISSUE THREAD

**Issue by PeterTheOne** [jdevoo/twecoll#38]
Python 2.7 will not be maintained past 2020.. https://pythonclock.org/

**Comment by PeterTheOne** [comment]
#43 tries to do this..

**Comment by jdevoo** [comment]
Thank you so much for looking into this! I will have a look as soon as I find time and see if we can complete this...

**Comment by lucahammer** [comment]
I am working on a Python 3 version, that uses Twython for the heavy lifting. It's basically written from scratch but uses the twecoll logic (same commands and similar file structure). I hope to have something to show over the next days.

**Comment by jdevoo** [comment]
closing this as I am not planning to migrate to Python 3
I have another version of this tool called [nucoll](https://github.com/jdevoo/nucoll) which is hopefully more convenient moving forward
