### ISSUE TITLE
add option to pass a list of screen_names

### ISSUE THREAD

**Issue by PeterTheOne** [jdevoo/twecoll#39]

**Comment by lucahammer** [comment]
Workaround until it gets implemented: Put the screennames in a file (including '@') and call it whatever.twt. Then you can use the "--query" argument to collect data about them and their network.

**Comment by PeterTheOne** [comment]
Thanks, I used a bash script to call twecoll in a loop for now. ^^°

**Comment by jdevoo** [comment]
init needs a single destination which conveniently groups the network under study. That can be a text file containing arbitrary handles, a single user, a list. Twecoll's CLI supports mixing with edgelist which can then look across all available data to study intersections of the networks processed by init/fetch.
