### ISSUE TITLE
No working init with large account

### ISSUE THREAD

**Issue by barripdmx** [jdevoo/twecoll#40]
python twecoll init vodafone_es --followers
HTTPError 429 at 17:30. Waiting 15m to resume...
HTTPError 429 at 17:46. Waiting 15m to resume...

Solution?

Best regards.
Barri

**Comment by lucahammer** [comment]
There is no solution, because you are hitting the Twitter API limit. It simply takes a lot of time.

https://github.com/jdevoo/twecoll/issues/24

**Comment by barripdmx** [comment]
:(  :( :(
No solution otherwise?

**Comment by barripdmx** [comment]
Yes working :)
PS C:\> cd python27
PS C:\python27> python twecoll init vodafone_es --followers
HTTPError 429 at 17:30. Waiting 15m to resume...
HTTPError 429 at 17:46. Waiting 15m to resume...
HTTPError 429 at 18:01. Waiting 15m to resume...
Processing 19717947,2446351,9856862,17767415,20228918,20074500,10903,16448616,20359206,20380132,17045233,20373449,17309111,17526509,12036682,16869970,15703780,17428750,14766090,20550195,20557728,19641418,16694371,16951874,18790369,19309488,20314307,14569896,16472077,18238788,11951862,21105328,17267346,18186920,15634642,20976709,21291577,21080594,17462835,6076652,21640894,21215023,17129629,21745592,14362119,19764618,21745782,6120472,21994814,13976432,17703300,18952037,19405795,22266667,22156456,21105308,22944444,17288095,23390202,14300298,23187005,18681373,2162141,22608510,19127526,19264271,24154662,19386232,1730551,17576729,25745039,25898386,26006028,25982252,6661672,24013143,6393752,15894868,14953125,26535047,26438566,25811752,3657871,23260501,26979139,25553197,11663142,21851197,27197362,635013,21096482,14242784,18809310,15465506,14570672,21982848,26597360,15263438,28585010,28790398...
