### ISSUE TITLE
Init Command does not fetch all the followers of the first account

### ISSUE THREAD

**Issue by watty62** [jdevoo/twecoll#46]
Hi,

I am just starting to use Twecoll, so this may be a problem of my making, but I do not think so. 

Following the instructions here, [https://medium.com/@Luca/how-to-collect-any-twitter-follower-network-with-the-python-script-twecoll-c482eeb61f77](https://medium.com/@Luca/how-to-collect-any-twitter-follower-network-with-the-python-script-twecoll-c482eeb61f77) I have started to use Twecoll.

I began by running 

`python twecoll init wingsscotland`

After the set up of the keys for the API it all seemed to work fine. 

The output was 
`Setup complete and /Users/ian/.twecoll created.
Processing 100 starting from 77821953...
Processing 65 starting from 404123976...
Done.`

if I open wingsscotland.dat in a text editor, I can see 165 lines. 

I expected it to start by gathering 55,208 followers (see https://twitter.com/WingsScotland/followers )

This looks like issue #36 - but may not be the same. 

I wonder if you can suggest anything to fix this please? 

Thanks

Ian

**Comment by jdevoo** [comment]
Thank you for trying twecoll Ian!
The default behavior for init is to retrieve friends. For followers you pass the option -o and it should start processing those 55k handles.

**Comment by watty62** [comment]
Ah - ok - that makes sense. Thank you very much for the clarification!
