### ISSUE TITLE
HTTP 401 error, but new setup does not work

### ISSUE THREAD

**Issue by georgloesel** [jdevoo/twecoll#47]
Hi,

I've used twecoll for some time with a rasberry pi  and a weekly run. 
Now I realized that the script is broken and by investigating I get the following.
When running the twecoll directly with twecoll.py init [myname] I get this 
HTTP Error 401: Authorization Required
twecoll list and 
twecoll edgelist
work

what can I do to get a proper init run? 

recreating the Twiiter Keys and trying a complete restart does not work 

Thanks for any hint

Georg

**Comment by jdevoo** [comment]
Georg, can you establish HTTPS connections from that board? When you say edgelist works without init working, it's odd. Edgelist starts by reading a .dat file that is produced by init. List is not a subcommand.

**Comment by jdevoo** [comment]
Can you try 'twecoll.py resolve georgloesel' and see what you get? Also useful would be the complete console input and output. Also check the readme as edgelist is called after fetch. The sequence should be init to get your friends followed by fetch to have twecoll fetch your friends' friends. Finally edgelist creates the GML file from that data.
