### ISSUE TITLE
Reverse auth credentials are invalid

### ISSUE THREAD

**Issue by JohnS0N2** [jdevoo/twecoll#49]
The above error is displayed when I try to run the script for the first time. I enter the api and secret key, then the script returns an url where we can authorize it. It then is supposed to return a PIN number, but instead we are given this error "Reverse auth credentials are invalid".

**Comment by JohnS0N2** [comment]
It seems this was happening because I had the callback enabled (for anyone who might have the same issue). So just create a new app without callback url and you will receive the pin.

**Comment by jdevoo** [comment]
Thank you!!
