### ISSUE TITLE
Question about the 'init' stage of twecoll

### ISSUE THREAD

**Issue by hudmb** [jdevoo/twecoll#52]
Hi,

When the 'init' stage is executed: -

python twecoll init jdevoo

Is this returning a list of jdevoo's *followers*. Or a list of people who jdevoo *follows* ?

Is there any way of specifying this at all if you require one or the other?

Similarly when the 'fetch' stage is run, can you specify whether you are looking at followers or following?

Thanks!

**Comment by lucahammer** [comment]
Per default init collects the followings (accounts the accounts follows). If you want to gather the followers you can use the -o (or --followers) argument.

Fetch only looks at what is in the .dat file which was created by the init command.

**Comment by hudmb** [comment]
Understood - thank you! Is there a list of these extra options that can be added. I couldn't find any in the wiki. Cheers.

**Comment by lucahammer** [comment]
You can use python "twecoll init -h" to show all options:

```
usage: twecoll init [-h] [-o] [-q] [-n] [-m L] [-f] screen_name

positional arguments:
  screen_name        Twitter screen name

optional arguments:
  -h, --help         show this help message and exit
  -o, --followers    retrieve followers (default: friends)
  -q, --query        extract handles from query (default: screen_name)
  -n, --nomention    ignore mentions from query (default: false)
  -m L, --members L  extract member handles from list named L
  -f, --force        ignore existing .dat file (default: False)

```

**Comment by lucahammer** [comment]
"init jdevoo -o" gets all followers and their basic info and puts it in jdevoo.dat.

"fetch jdevoo" gets the followings (only the IDs) of each of the accounts in jdevoo.dat and saves them in a sub directory as id_of_the_account.f.

**Comment by hudmb** [comment]
Super - thank you for the explanation. I was trying to get my head around whether it was follower or following relationships that were being extracted. Thanks!

**Comment by lucahammer** [comment]
The only time when this matters are private accounts. For everyone else in the graph you have all followings as well as all followers within the graph.
