### ISSUE TITLE
"Diff'ing sets" question related to "intersection of sets"

### ISSUE THREAD

**Issue by hudmb** [jdevoo/twecoll#53]
Hi there,

Forgive my lack of skill here - I'm not a programmer so things such as this are quite hard for me to grasp. In the wiki you detail a method of diff'ing two .dat files using this method: -

`awk -F ',' 'NR==FNR {m[$1]++; next} !m[$1]' dr_rick.dat jdevoo.dat
`

Could I ask how you could alter this in order to find the **intersect** between two .dat files? I.e. finding out who are friends (or followers) of both accounts?

Thanks in advance!

**Comment by hudmb** [comment]
Could this work?

awk -F, 'NR==FNR{a[$1]++;next} (a[$1])' File1.dat File2.dat >>intersect.scv

**Comment by jdevoo** [comment]
yes it would;
essentially, the NR==NFR condition applies to the first file only and creates a lookup array; the second thing in quotes is applied to the first file but doesn't return anything. It will work on the second file and using the lookup array, match rows for which the first item can be found in the array = intersection.
