### ISSUE TITLE
Attribute "user_id" does not conform to GML specification

### ISSUE THREAD

**Issue by watty62** [jdevoo/twecoll#56]
Hi 

I recently ran into an issue (documented [here](https://stackoverflow.com/questions/51612124/networkx-key-error-when-writing-gml-file) where on reading in GML files created by Twecoll, and merging them using NetworkX , I could not then write the resultant data back out as GML. 

It turns out that, I am told (but cannot find a reference) that GML does not support underscores on attribute names. 

NetworkX developers are loose with the reading of GML (i.e. they allow non-compliant GML to be read in) but they do not allow it to be written. 

I though that you would want to know this.

**Comment by jdevoo** [comment]
indeed! I looked it up in [http://www.fim.uni-passau.de/fileadmin/files/lehrstuhl/brandenburg/projekte/gml/gml-technical-report.pdf](http://www.fim.uni-passau.de/fileadmin/files/lehrstuhl/brandenburg/projekte/gml/gml-technical-report.pdf)
Thank you! Will keep it open until I make this change.

**Comment by jdevoo** [comment]
done
