### ISSUE TITLE
Only 50% followers

### ISSUE THREAD

**Issue by barripdmx** [jdevoo/twecoll#57]
Hi,
In the command "python twecoll init xxxxxxxx --followers" only extract 50% of followers.
It is normal?

Best regards
barri

**Comment by jdevoo** [comment]
only if xxxxxxxx has 50% protected accounts which will be skipped

**Comment by barripdmx** [comment]
It is not this case.
The acoount "xxxxxxxx" has a total 46075 follower
accounts protect: 3489 
I do not know why he does not collect more accounts.

**Comment by jdevoo** [comment]
can you share the handle? have you re-run init with --force so it re-creates the .dat file?

**Comment by barripdmx** [comment]
With --force they extract up to 32500. If the account is 46100 and there are 3500 blocked, the result is good. :)
My English is very bad. What do you mean with: "can you share the handle?"

**Comment by jdevoo** [comment]
no worries - I meant to ask if you can put the twitter account (or handle) here I can then try to reproduce the problem; it should really be able to download all except blocked...

**Comment by barripdmx** [comment]
account: anticapi

**Comment by jdevoo** [comment]
could not reproduce; I ran `twecoll init -o anticapi` and obtained after a while a file anticapi.dat with 46079 rows.
How about trying that again after you remove the fdat directory and the anticapi.dat file?

**Comment by barripdmx** [comment]
Okay. I try again
The option - o is it new? That makes?

**Comment by barripdmx** [comment]
I have tried again starting from 0. with _twecoll init -o anticapi_
I get the same: 32,496. :(
What version of twecoll do you use?
Can it be the twitter API?

**Comment by jdevoo** [comment]
so strange - I use the latest version on GitHub from 21 July with Python 2.7.12 on Ubuntu.
Just re-ran the command I wrote above with -f to force API requests and arrive at the current count (according to tweetdeck) of 46087+1 in about 1h30

below the last few output rows...
```
Processing 100 starting from 927459191836545025...
Processing 100 starting from 1728935226...
Processing 100 starting from 2984638990...
Processing 100 starting from 2557409821...
Processing 100 starting from 955606485848985600...
Processing 100 starting from 401663325...
Processing 100 starting from 195309437...
Processing 100 starting from 300589755...
Processing 100 starting from 429109008...
Processing 100 starting from 847078475647389696...
Processing 100 starting from 1135283509...
Processing 100 starting from 869590160941486081...
Processing 100 starting from 994941846...
Processing 100 starting from 2867063745...
Processing 100 starting from 225208940...
Processing 100 starting from 433434040...
Processing 100 starting from 977250514156052480...
Processing 100 starting from 728735970221133824...
Processing 100 starting from 410908396...
Processing 100 starting from 267611913...
Processing 100 starting from 921784721402662912...
Processing 100 starting from 830553048...
Processing 100 starting from 420533061...
Processing 100 starting from 514367935...
Processing 100 starting from 711613673303838720...
Processing 100 starting from 518365942...
Processing 100 starting from 1140492012...
Processing 100 starting from 372901531...
Processing 100 starting from 805438450107351041...
Processing 100 starting from 1226261826...
Processing 100 starting from 84542742...
Processing 100 starting from 1029877992321941504...
Processing 100 starting from 914528952735223808...
Processing 90 starting from 50134116...
Done.
```
