### ISSUE TITLE
[Question] Fetch to Skip .f files already created

### ISSUE THREAD

**Issue by theDataFox** [jdevoo/twecoll#58]
Hey jdevoo thank you for this amazing tool.

I would like to know how I would go about skipping the .f files in the `fdat` folder. If that's possible? I am querying an account with ~430k followers and so if I could skip the ones that have already been populated in the fdat folder that would be beneficial, but I'm not sure how to do this. 

It appears that at present the `fetch` function will still call the API for ones that are in the `fdat` folder. This can also be confirmed by the fact that when the script is running it will say 430,000 remaining etc.

Thank you

**Comment by theDataFox** [comment]
Oh apologies, that is what the `--force` flag is for

**Comment by lucahammer** [comment]
Skipping accounts with existing .f files is the default behavior. -f /--force overrides this and fetches new data for every account.

You see 430k remaining because twecoll looks if the .f file already exists as goes through the list of accounts.

**Comment by theDataFox** [comment]
Is it correct to see this behaviour? When the .f files already exist?

Processing 2811101022...
HTTPError 401 with 2811101022. Skipping...
Processing 1041749005078867970...
HTTPError 401 with 1041749005078867970. Skipping...
Processing 809333277777608704...
HTTPError 401 with 809333277777608704. Skipping...
Processing 186993982...
HTTPError 401 with 186993982. Skipping...
Processing 508925997...
HTTPError 401 with 508925997. Skipping...
Processing 1040319177607790592...

**Comment by jdevoo** [comment]
what happens when you run `twecoll resolve 2811101022`

**Comment by theDataFox** [comment]
```
MB98765 (148 friends | 35 followers | 0 memberships | 378 tweets)
Done.

```

**Comment by jdevoo** [comment]
seems your credentials are working - that 401 error seems to indicate something with credentials is going wrong - could the .twecoll have been modified over the process of fetching?
