### ISSUE TITLE
[Errno 22] Invalid argument - Fetch Function

### ISSUE THREAD

**Issue by theDataFox** [jdevoo/twecoll#59]
Hey, I seem to be getting this error on `fetch`. The script will then stop running once it occurs.

It appeared as below:

Processing 508925997...
HTTPError 429 at 10:26. Waiting -1m to resume (433922 items left)...[Errno 22] Invalid argument

**Comment by jdevoo** [comment]
can you provide details on your setup, the way you ran init and fetch and perhaps the handle so I can reproduce?

**Comment by theDataFox** [comment]
Sure, the handle is @MartinSLewis. 

Fetch is running with no additional arguments and the issue occurs on both Win10 and Linux Debian.

I feel like its related to this part of the script within `def fetch()`
```python
elif hasattr(e, 'code') and e.code in WAIT_CODES:
    waiting_time = int(e.headers['x-rate-limit-reset']) - int(round(time.time())) + random.randint(10,30)
```
As if I hard code `waiting_time=900` for example the error does not occur.

**Comment by jdevoo** [comment]
thank you! and you are running this on the friends or followers?

**Comment by theDataFox** [comment]
No worries!

I think it was a specific amount of time after a few hours of running the script the `waiting_time` variable becomes equal to -1 for some reason causing the above error. Prior to this twecoll fetches the handles correctly.

**Comment by jdevoo** [comment]
Ok I will try to reproduce as I had changed recently from constant waiting time (15 min hard-coded) to header-driven...

**Comment by jdevoo** [comment]
I was not able to reproduce this unfortunately.
