### ISSUE TITLE
"Authorize the script" step didn't return a PIN

### ISSUE THREAD

**Issue by tenorslowworm** [jdevoo/twecoll#60]
When I executed the "(2) Now, open this link and authorize the script..." step (by opening the provided URL in a browser) I wasn't presented with a PIN after authorizing. Instead, the browser just displayed a brief message about redirecting to my app, and then did so. (I'm pretty sure I saw no PIN on the brief interstitial page.)

I tried this in a browser where I was already logged in to the app's associated Twitter account (in which case, I was simply asked to grant access) and then ran the script again, and this time opened the URL in an incognito window. (Where I had to log into the account again.) Same results both times.

Command I ran: python twecoll init AuthorFreeman --followers

I'll attach a screenshot of the auth screen I saw.

Thanks for any help you can give me.

![screen shot 2018-10-14 at 12 40 38 am](https://user-images.githubusercontent.com/1794435/46913858-35168d00-cf4a-11e8-9d5c-f9f77fc59855.png)

**Comment by jdevoo** [comment]
can you check the way you set up twecoll as an app? Callback URL is empty right?
Luca has [a post](https://lucahammer.com/2016/09/07/how-to-collect-any-twitter-follower-network-with-the-python-script-twecoll/) with a small screen recording showing the steps; perhaps it helps.

**Comment by tenorslowworm** [comment]
Thanks, that was it! I was reusing an existing test app just out of convenience, but it had a callback url. Deleting it got things working.
