### ISSUE TITLE
HTTP ERROR 401 : Authorization Required

### ISSUE THREAD

**Issue by saish29** [jdevoo/twecoll#61]
Hi jdevoo, I am trying to use twecoll from the last two weeks from now. I have an approved developer account and also have created an app on the dev.twitter.com for the Twitter API consumer keys. I run the code using Windows Powershell, using python 2.7. Although I am still facing the HTTP error 401. (Snap attached). I am using the latest version of twecoll. Please help.
![error](https://user-images.githubusercontent.com/37171427/47715111-c08b6000-dc64-11e8-8089-8a82939d425e.PNG)

**Comment by jdevoo** [comment]
Hi! Perhaps this [post ](https://lucahammer.com/2016/09/07/how-to-collect-any-twitter-follower-network-with-the-python-script-twecoll/)can help to re-check the set up steps. You have for instance a .twecoll file in your home directory with 4 lines. The callback URL in the Twitter Apps dashboard should be empty.
